console:
  max_message_size_bytes: 409600
logger:
  level: "DEBUG"
session:
  token_expiry_sec: 7200 # 2 hours
  refresh_token_expiry_sec: 86400 # 24 hours
  encryption_key: "YM0fahhp2aW9dcuqq2Z6gFj6AvyaJLAfMMofaCmJ91c="
socket:
  max_message_size_bytes: 4096 # reserved buffer
  max_request_size_bytes: 131072
runtime:
  path: /nakama/data/modules

