// Copyright 2020 The Nakama Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: proto/common_api.proto

// The realtime protocol for the template match engine.

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TypeChat int32

const (
	TypeChat_TYPE_CHAT_UNSPECIFIED TypeChat = 0
	TypeChat_TYPE_CHAT_ROOM        TypeChat = 1
	TypeChat_TYPE_CHAT_DIRECTMSG   TypeChat = 2
	TypeChat_TYPE_CHAT_GROUUP      TypeChat = 3
)

// Enum value maps for TypeChat.
var (
	TypeChat_name = map[int32]string{
		0: "TYPE_CHAT_UNSPECIFIED",
		1: "TYPE_CHAT_ROOM",
		2: "TYPE_CHAT_DIRECTMSG",
		3: "TYPE_CHAT_GROUUP",
	}
	TypeChat_value = map[string]int32{
		"TYPE_CHAT_UNSPECIFIED": 0,
		"TYPE_CHAT_ROOM":        1,
		"TYPE_CHAT_DIRECTMSG":   2,
		"TYPE_CHAT_GROUUP":      3,
	}
)

func (x TypeChat) Enum() *TypeChat {
	p := new(TypeChat)
	*p = x
	return p
}

func (x TypeChat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeChat) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_api_proto_enumTypes[0].Descriptor()
}

func (TypeChat) Type() protoreflect.EnumType {
	return &file_proto_common_api_proto_enumTypes[0]
}

func (x TypeChat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeChat.Descriptor instead.
func (TypeChat) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{0}
}

type ExchangeStatus int32

const (
	ExchangeStatus_EXCHANGE_STATUS_UNSPECIFIED    ExchangeStatus = 0
	ExchangeStatus_EXCHANGE_STATUS_WAITING        ExchangeStatus = 1
	ExchangeStatus_EXCHANGE_STATUS_CANCEL_BY_USER ExchangeStatus = 2
	ExchangeStatus_EXCHANGE_STATUS_PENDING        ExchangeStatus = 3
	ExchangeStatus_EXCHANGE_STATUS_DONE           ExchangeStatus = 4
	ExchangeStatus_EXCHANGE_STATUS_REJECT         ExchangeStatus = 5
)

// Enum value maps for ExchangeStatus.
var (
	ExchangeStatus_name = map[int32]string{
		0: "EXCHANGE_STATUS_UNSPECIFIED",
		1: "EXCHANGE_STATUS_WAITING",
		2: "EXCHANGE_STATUS_CANCEL_BY_USER",
		3: "EXCHANGE_STATUS_PENDING",
		4: "EXCHANGE_STATUS_DONE",
		5: "EXCHANGE_STATUS_REJECT",
	}
	ExchangeStatus_value = map[string]int32{
		"EXCHANGE_STATUS_UNSPECIFIED":    0,
		"EXCHANGE_STATUS_WAITING":        1,
		"EXCHANGE_STATUS_CANCEL_BY_USER": 2,
		"EXCHANGE_STATUS_PENDING":        3,
		"EXCHANGE_STATUS_DONE":           4,
		"EXCHANGE_STATUS_REJECT":         5,
	}
)

func (x ExchangeStatus) Enum() *ExchangeStatus {
	p := new(ExchangeStatus)
	*p = x
	return p
}

func (x ExchangeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExchangeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_api_proto_enumTypes[1].Descriptor()
}

func (ExchangeStatus) Type() protoreflect.EnumType {
	return &file_proto_common_api_proto_enumTypes[1]
}

func (x ExchangeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExchangeStatus.Descriptor instead.
func (ExchangeStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{1}
}

type Game struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string  `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Active  bool    `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	LobbyId string  `protobuf:"bytes,3,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	Layout  *Layout `protobuf:"bytes,4,opt,name=layout,proto3" json:"layout,omitempty"`
}

func (x *Game) Reset() {
	*x = Game{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{0}
}

func (x *Game) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Game) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Game) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *Game) GetLayout() *Layout {
	if x != nil {
		return x.Layout
	}
	return nil
}

type Layout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Col     int32 `protobuf:"varint,1,opt,name=col,proto3" json:"col,omitempty"`
	Row     int32 `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	ColSpan int32 `protobuf:"varint,3,opt,name=col_span,json=colSpan,proto3" json:"col_span,omitempty"`
	RowSpan int32 `protobuf:"varint,4,opt,name=row_span,json=rowSpan,proto3" json:"row_span,omitempty"`
}

func (x *Layout) Reset() {
	*x = Layout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Layout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layout) ProtoMessage() {}

func (x *Layout) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layout.ProtoReflect.Descriptor instead.
func (*Layout) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{1}
}

func (x *Layout) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *Layout) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *Layout) GetColSpan() int32 {
	if x != nil {
		return x.ColSpan
	}
	return 0
}

func (x *Layout) GetRowSpan() int32 {
	if x != nil {
		return x.RowSpan
	}
	return 0
}

type GameListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Games []*Game `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
}

func (x *GameListResponse) Reset() {
	*x = GameListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameListResponse) ProtoMessage() {}

func (x *GameListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameListResponse.ProtoReflect.Descriptor instead.
func (*GameListResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{2}
}

func (x *GameListResponse) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

type BetListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *BetListRequest) Reset() {
	*x = BetListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetListRequest) ProtoMessage() {}

func (x *BetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetListRequest.ProtoReflect.Descriptor instead.
func (*BetListRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{3}
}

func (x *BetListRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type BetListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bets []int32 `protobuf:"varint,1,rep,packed,name=bets,proto3" json:"bets,omitempty"`
}

func (x *BetListResponse) Reset() {
	*x = BetListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetListResponse) ProtoMessage() {}

func (x *BetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetListResponse.ProtoReflect.Descriptor instead.
func (*BetListResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{4}
}

func (x *BetListResponse) GetBets() []int32 {
	if x != nil {
		return x.Bets
	}
	return nil
}

type Chat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeChat TypeChat `protobuf:"varint,1,opt,name=type_chat,json=typeChat,proto3,enum=api.TypeChat" json:"type_chat,omitempty"`
	Id       string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Content  string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Chat) Reset() {
	*x = Chat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{5}
}

func (x *Chat) GetTypeChat() TypeChat {
	if x != nil {
		return x.TypeChat
	}
	return TypeChat_TYPE_CHAT_UNSPECIFIED
}

func (x *Chat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chat) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type FreeChip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderId    string `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	RecipientId string `protobuf:"bytes,3,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Title       string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content     string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Chips       int64  `protobuf:"varint,6,opt,name=chips,proto3" json:"chips,omitempty"`
	Claimable   bool   `protobuf:"varint,7,opt,name=claimable,proto3" json:"claimable,omitempty"`
}

func (x *FreeChip) Reset() {
	*x = FreeChip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FreeChip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeChip) ProtoMessage() {}

func (x *FreeChip) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeChip.ProtoReflect.Descriptor instead.
func (*FreeChip) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{6}
}

func (x *FreeChip) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FreeChip) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *FreeChip) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *FreeChip) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FreeChip) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FreeChip) GetChips() int64 {
	if x != nil {
		return x.Chips
	}
	return 0
}

func (x *FreeChip) GetClaimable() bool {
	if x != nil {
		return x.Claimable
	}
	return false
}

type FreeChipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit  int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cusor  string `protobuf:"bytes,3,opt,name=cusor,proto3" json:"cusor,omitempty"`
}

func (x *FreeChipRequest) Reset() {
	*x = FreeChipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FreeChipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeChipRequest) ProtoMessage() {}

func (x *FreeChipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeChipRequest.ProtoReflect.Descriptor instead.
func (*FreeChipRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{7}
}

func (x *FreeChipRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FreeChipRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FreeChipRequest) GetCusor() string {
	if x != nil {
		return x.Cusor
	}
	return ""
}

type ListFreeChip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Freechips []*FreeChip `protobuf:"bytes,1,rep,name=freechips,proto3" json:"freechips,omitempty"`
	NextCusor string      `protobuf:"bytes,2,opt,name=next_cusor,json=nextCusor,proto3" json:"next_cusor,omitempty"`
	PrevCusor string      `protobuf:"bytes,3,opt,name=prev_cusor,json=prevCusor,proto3" json:"prev_cusor,omitempty"`
	Total     int64       `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Offset    int64       `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit     int64       `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListFreeChip) Reset() {
	*x = ListFreeChip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFreeChip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFreeChip) ProtoMessage() {}

func (x *ListFreeChip) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFreeChip.ProtoReflect.Descriptor instead.
func (*ListFreeChip) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{8}
}

func (x *ListFreeChip) GetFreechips() []*FreeChip {
	if x != nil {
		return x.Freechips
	}
	return nil
}

func (x *ListFreeChip) GetNextCusor() string {
	if x != nil {
		return x.NextCusor
	}
	return ""
}

func (x *ListFreeChip) GetPrevCusor() string {
	if x != nil {
		return x.PrevCusor
	}
	return ""
}

func (x *ListFreeChip) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListFreeChip) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListFreeChip) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Deal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Chips       int64  `protobuf:"varint,2,opt,name=chips,proto3" json:"chips,omitempty"`
	AmountChips int64  `protobuf:"varint,3,opt,name=amount_chips,json=amountChips,proto3" json:"amount_chips,omitempty"`
	Bonus       int64  `protobuf:"varint,4,opt,name=bonus,proto3" json:"bonus,omitempty"`
	Price       string `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Name        string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Currency    string `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	Percent     string `protobuf:"bytes,8,opt,name=percent,proto3" json:"percent,omitempty"`
	ChipPerUnit int64  `protobuf:"varint,9,opt,name=chip_per_unit,json=chipPerUnit,proto3" json:"chip_per_unit,omitempty"`
}

func (x *Deal) Reset() {
	*x = Deal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deal) ProtoMessage() {}

func (x *Deal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deal.ProtoReflect.Descriptor instead.
func (*Deal) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{9}
}

func (x *Deal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Deal) GetChips() int64 {
	if x != nil {
		return x.Chips
	}
	return 0
}

func (x *Deal) GetAmountChips() int64 {
	if x != nil {
		return x.AmountChips
	}
	return 0
}

func (x *Deal) GetBonus() int64 {
	if x != nil {
		return x.Bonus
	}
	return 0
}

func (x *Deal) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Deal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Deal) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Deal) GetPercent() string {
	if x != nil {
		return x.Percent
	}
	return ""
}

func (x *Deal) GetChipPerUnit() int64 {
	if x != nil {
		return x.ChipPerUnit
	}
	return 0
}

type DealInShop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Best    *Deal   `protobuf:"bytes,1,opt,name=best,proto3" json:"best,omitempty"`
	Iaps    []*Deal `protobuf:"bytes,2,rep,name=iaps,proto3" json:"iaps,omitempty"`
	Gcashes []*Deal `protobuf:"bytes,3,rep,name=gcashes,proto3" json:"gcashes,omitempty"`
	Sms     []*Deal `protobuf:"bytes,4,rep,name=sms,proto3" json:"sms,omitempty"`
}

func (x *DealInShop) Reset() {
	*x = DealInShop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DealInShop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealInShop) ProtoMessage() {}

func (x *DealInShop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealInShop.ProtoReflect.Descriptor instead.
func (*DealInShop) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{10}
}

func (x *DealInShop) GetBest() *Deal {
	if x != nil {
		return x.Best
	}
	return nil
}

func (x *DealInShop) GetIaps() []*Deal {
	if x != nil {
		return x.Iaps
	}
	return nil
}

func (x *DealInShop) GetGcashes() []*Deal {
	if x != nil {
		return x.Gcashes
	}
	return nil
}

func (x *DealInShop) GetSms() []*Deal {
	if x != nil {
		return x.Sms
	}
	return nil
}

type LeaderBoardRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameCode string `protobuf:"bytes,1,opt,name=game_code,json=gameCode,proto3" json:"game_code,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score    int64  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *LeaderBoardRecord) Reset() {
	*x = LeaderBoardRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderBoardRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderBoardRecord) ProtoMessage() {}

func (x *LeaderBoardRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderBoardRecord.ProtoReflect.Descriptor instead.
func (*LeaderBoardRecord) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{11}
}

func (x *LeaderBoardRecord) GetGameCode() string {
	if x != nil {
		return x.GameCode
	}
	return ""
}

func (x *LeaderBoardRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaderBoardRecord) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type ExchangeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdDeal           string `protobuf:"bytes,2,opt,name=id_deal,json=idDeal,proto3" json:"id_deal,omitempty"`
	Chips            int64  `protobuf:"varint,3,opt,name=chips,proto3" json:"chips,omitempty"`
	Price            string `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Status           int64  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Unlock           int32  `protobuf:"varint,6,opt,name=unlock,proto3" json:"unlock,omitempty"`
	CashId           string `protobuf:"bytes,7,opt,name=cash_id,json=cashId,proto3" json:"cash_id,omitempty"`
	CashType         string `protobuf:"bytes,8,opt,name=cash_type,json=cashType,proto3" json:"cash_type,omitempty"`
	UserIdRequest    string `protobuf:"bytes,9,opt,name=user_id_request,json=userIdRequest,proto3" json:"user_id_request,omitempty"`
	UserNameRequest  string `protobuf:"bytes,10,opt,name=user_name_request,json=userNameRequest,proto3" json:"user_name_request,omitempty"`
	VipLv            int64  `protobuf:"varint,11,opt,name=vip_lv,json=vipLv,proto3" json:"vip_lv,omitempty"`
	DeviceId         string `protobuf:"bytes,12,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	UserIdHandling   string `protobuf:"bytes,13,opt,name=user_id_handling,json=userIdHandling,proto3" json:"user_id_handling,omitempty"`
	UserNameHandling string `protobuf:"bytes,14,opt,name=user_name_handling,json=userNameHandling,proto3" json:"user_name_handling,omitempty"`
	Reason           string `protobuf:"bytes,15,opt,name=reason,proto3" json:"reason,omitempty"`
	Cursor           string `protobuf:"bytes,16,opt,name=cursor,proto3" json:"cursor,omitempty"`
	CreateTime       int64  `protobuf:"varint,17,opt,name=createTime,proto3" json:"createTime,omitempty"`
}

func (x *ExchangeInfo) Reset() {
	*x = ExchangeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeInfo) ProtoMessage() {}

func (x *ExchangeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeInfo.ProtoReflect.Descriptor instead.
func (*ExchangeInfo) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{12}
}

func (x *ExchangeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExchangeInfo) GetIdDeal() string {
	if x != nil {
		return x.IdDeal
	}
	return ""
}

func (x *ExchangeInfo) GetChips() int64 {
	if x != nil {
		return x.Chips
	}
	return 0
}

func (x *ExchangeInfo) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *ExchangeInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ExchangeInfo) GetUnlock() int32 {
	if x != nil {
		return x.Unlock
	}
	return 0
}

func (x *ExchangeInfo) GetCashId() string {
	if x != nil {
		return x.CashId
	}
	return ""
}

func (x *ExchangeInfo) GetCashType() string {
	if x != nil {
		return x.CashType
	}
	return ""
}

func (x *ExchangeInfo) GetUserIdRequest() string {
	if x != nil {
		return x.UserIdRequest
	}
	return ""
}

func (x *ExchangeInfo) GetUserNameRequest() string {
	if x != nil {
		return x.UserNameRequest
	}
	return ""
}

func (x *ExchangeInfo) GetVipLv() int64 {
	if x != nil {
		return x.VipLv
	}
	return 0
}

func (x *ExchangeInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ExchangeInfo) GetUserIdHandling() string {
	if x != nil {
		return x.UserIdHandling
	}
	return ""
}

func (x *ExchangeInfo) GetUserNameHandling() string {
	if x != nil {
		return x.UserNameHandling
	}
	return ""
}

func (x *ExchangeInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ExchangeInfo) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ExchangeInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type ExchangeDealInShop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gcashes []*Deal `protobuf:"bytes,1,rep,name=gcashes,proto3" json:"gcashes,omitempty"`
}

func (x *ExchangeDealInShop) Reset() {
	*x = ExchangeDealInShop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeDealInShop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeDealInShop) ProtoMessage() {}

func (x *ExchangeDealInShop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeDealInShop.ProtoReflect.Descriptor instead.
func (*ExchangeDealInShop) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{13}
}

func (x *ExchangeDealInShop) GetGcashes() []*Deal {
	if x != nil {
		return x.Gcashes
	}
	return nil
}

type ListExchangeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExchangeInfos []*ExchangeInfo `protobuf:"bytes,1,rep,name=exchange_infos,json=exchangeInfos,proto3" json:"exchange_infos,omitempty"`
	NextCusor     string          `protobuf:"bytes,2,opt,name=next_cusor,json=nextCusor,proto3" json:"next_cusor,omitempty"`
	PrevCusor     string          `protobuf:"bytes,3,opt,name=prev_cusor,json=prevCusor,proto3" json:"prev_cusor,omitempty"`
	Total         int64           `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Offset        int64           `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int64           `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	From          int64           `protobuf:"varint,7,opt,name=from,proto3" json:"from,omitempty"`
	To            int64           `protobuf:"varint,8,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *ListExchangeInfo) Reset() {
	*x = ListExchangeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListExchangeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExchangeInfo) ProtoMessage() {}

func (x *ListExchangeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExchangeInfo.ProtoReflect.Descriptor instead.
func (*ListExchangeInfo) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{14}
}

func (x *ListExchangeInfo) GetExchangeInfos() []*ExchangeInfo {
	if x != nil {
		return x.ExchangeInfos
	}
	return nil
}

func (x *ListExchangeInfo) GetNextCusor() string {
	if x != nil {
		return x.NextCusor
	}
	return ""
}

func (x *ListExchangeInfo) GetPrevCusor() string {
	if x != nil {
		return x.PrevCusor
	}
	return ""
}

func (x *ListExchangeInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListExchangeInfo) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListExchangeInfo) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListExchangeInfo) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ListExchangeInfo) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

type ExchangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserIdRequest string `protobuf:"bytes,2,opt,name=user_id_request,json=userIdRequest,proto3" json:"user_id_request,omitempty"`
	Limit         int64  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	From          int64  `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`
	To            int64  `protobuf:"varint,5,opt,name=to,proto3" json:"to,omitempty"`
	Cusor         string `protobuf:"bytes,6,opt,name=cusor,proto3" json:"cusor,omitempty"`
	CashType      string `protobuf:"bytes,9,opt,name=cash_type,json=cashType,proto3" json:"cash_type,omitempty"`
}

func (x *ExchangeRequest) Reset() {
	*x = ExchangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRequest) ProtoMessage() {}

func (x *ExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{15}
}

func (x *ExchangeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExchangeRequest) GetUserIdRequest() string {
	if x != nil {
		return x.UserIdRequest
	}
	return ""
}

func (x *ExchangeRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ExchangeRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ExchangeRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *ExchangeRequest) GetCusor() string {
	if x != nil {
		return x.Cusor
	}
	return ""
}

func (x *ExchangeRequest) GetCashType() string {
	if x != nil {
		return x.CashType
	}
	return ""
}

type Reward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chips                int64   `protobuf:"varint,1,opt,name=chips,proto3" json:"chips,omitempty"`
	PercentBonus         float32 `protobuf:"fixed32,2,opt,name=percent_bonus,json=percentBonus,proto3" json:"percent_bonus,omitempty"`
	BonusChips           int64   `protobuf:"varint,3,opt,name=bonus_chips,json=bonusChips,proto3" json:"bonus_chips,omitempty"`
	TotalChips           int64   `protobuf:"varint,4,opt,name=total_chips,json=totalChips,proto3" json:"total_chips,omitempty"`
	Streak               int64   `protobuf:"varint,5,opt,name=streak,proto3" json:"streak,omitempty"`
	SecsOnline           int64   `protobuf:"varint,6,opt,name=secs_online,json=secsOnline,proto3" json:"secs_online,omitempty"`
	SecsOnlineAfterClaim int64   `protobuf:"varint,7,opt,name=secs_online_after_claim,json=secsOnlineAfterClaim,proto3" json:"secs_online_after_claim,omitempty"`
	CanClaim             bool    `protobuf:"varint,8,opt,name=can_claim,json=canClaim,proto3" json:"can_claim,omitempty"`
	NumClaim             int64   `protobuf:"varint,9,opt,name=num_claim,json=numClaim,proto3" json:"num_claim,omitempty"`
	LastClaimUnix        int64   `protobuf:"varint,10,opt,name=last_claim_unix,json=lastClaimUnix,proto3" json:"last_claim_unix,omitempty"`
}

func (x *Reward) Reset() {
	*x = Reward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reward) ProtoMessage() {}

func (x *Reward) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reward.ProtoReflect.Descriptor instead.
func (*Reward) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{16}
}

func (x *Reward) GetChips() int64 {
	if x != nil {
		return x.Chips
	}
	return 0
}

func (x *Reward) GetPercentBonus() float32 {
	if x != nil {
		return x.PercentBonus
	}
	return 0
}

func (x *Reward) GetBonusChips() int64 {
	if x != nil {
		return x.BonusChips
	}
	return 0
}

func (x *Reward) GetTotalChips() int64 {
	if x != nil {
		return x.TotalChips
	}
	return 0
}

func (x *Reward) GetStreak() int64 {
	if x != nil {
		return x.Streak
	}
	return 0
}

func (x *Reward) GetSecsOnline() int64 {
	if x != nil {
		return x.SecsOnline
	}
	return 0
}

func (x *Reward) GetSecsOnlineAfterClaim() int64 {
	if x != nil {
		return x.SecsOnlineAfterClaim
	}
	return 0
}

func (x *Reward) GetCanClaim() bool {
	if x != nil {
		return x.CanClaim
	}
	return false
}

func (x *Reward) GetNumClaim() int64 {
	if x != nil {
		return x.NumClaim
	}
	return 0
}

func (x *Reward) GetLastClaimUnix() int64 {
	if x != nil {
		return x.LastClaimUnix
	}
	return 0
}

type DayReward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IndayReward   *Reward   `protobuf:"bytes,1,opt,name=inday_reward,json=indayReward,proto3" json:"inday_reward,omitempty"`
	OnlineReward  *Reward   `protobuf:"bytes,2,opt,name=online_reward,json=onlineReward,proto3" json:"online_reward,omitempty"`
	OnlineRewards []*Reward `protobuf:"bytes,3,rep,name=online_rewards,json=onlineRewards,proto3" json:"online_rewards,omitempty"`
}

func (x *DayReward) Reset() {
	*x = DayReward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DayReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayReward) ProtoMessage() {}

func (x *DayReward) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayReward.ProtoReflect.Descriptor instead.
func (*DayReward) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{17}
}

func (x *DayReward) GetIndayReward() *Reward {
	if x != nil {
		return x.IndayReward
	}
	return nil
}

func (x *DayReward) GetOnlineReward() *Reward {
	if x != nil {
		return x.OnlineReward
	}
	return nil
}

func (x *DayReward) GetOnlineRewards() []*Reward {
	if x != nil {
		return x.OnlineRewards
	}
	return nil
}

type DailyReward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dailies []*DayReward `protobuf:"bytes,1,rep,name=dailies,proto3" json:"dailies,omitempty"`
}

func (x *DailyReward) Reset() {
	*x = DailyReward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DailyReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyReward) ProtoMessage() {}

func (x *DailyReward) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyReward.ProtoReflect.Descriptor instead.
func (*DailyReward) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{18}
}

func (x *DailyReward) GetDailies() []*DayReward {
	if x != nil {
		return x.Dailies
	}
	return nil
}

var File_proto_common_api_proto protoreflect.FileDescriptor

var file_proto_common_api_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x72, 0x0a,
	0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x06,
	0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75,
	0x74, 0x22, 0x62, 0x0a, 0x06, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63,
	0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x6f, 0x6c, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x12,
	0x19, 0x0a, 0x08, 0x63, 0x6f, 0x6c, 0x5f, 0x73, 0x70, 0x61, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x63, 0x6f, 0x6c, 0x53, 0x70, 0x61, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f,
	0x77, 0x5f, 0x73, 0x70, 0x61, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x6f,
	0x77, 0x53, 0x70, 0x61, 0x6e, 0x22, 0x33, 0x0a, 0x10, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x67, 0x61, 0x6d,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x05, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x24, 0x0a, 0x0e, 0x42, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0x25, 0x0a, 0x0f, 0x42, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x04, 0x62, 0x65, 0x74, 0x73, 0x22, 0x5c, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12,
	0x2a, 0x0a, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x43, 0x68, 0x61,
	0x74, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x43, 0x68, 0x61, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xbe, 0x01, 0x0a, 0x08, 0x46, 0x72, 0x65, 0x65, 0x43, 0x68,
	0x69, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x69, 0x70, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x63, 0x68, 0x69, 0x70, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x61, 0x69,
	0x6d, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6c, 0x61,
	0x69, 0x6d, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x56, 0x0a, 0x0f, 0x46, 0x72, 0x65, 0x65, 0x43, 0x68,
	0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x75, 0x73, 0x6f,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x75, 0x73, 0x6f, 0x72, 0x22, 0xbd,
	0x01, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x65, 0x65, 0x43, 0x68, 0x69, 0x70, 0x12,
	0x2b, 0x0a, 0x09, 0x66, 0x72, 0x65, 0x65, 0x63, 0x68, 0x69, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x72, 0x65, 0x65, 0x43, 0x68, 0x69,
	0x70, 0x52, 0x09, 0x66, 0x72, 0x65, 0x65, 0x63, 0x68, 0x69, 0x70, 0x73, 0x12, 0x1d, 0x0a, 0x0a,
	0x6e, 0x65, 0x78, 0x74, 0x5f, 0x63, 0x75, 0x73, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x43, 0x75, 0x73, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x72, 0x65, 0x76, 0x5f, 0x63, 0x75, 0x73, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x72, 0x65, 0x76, 0x43, 0x75, 0x73, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xe9,
	0x01, 0x0a, 0x04, 0x44, 0x65, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x69, 0x70, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x68, 0x69, 0x70, 0x73, 0x12, 0x21, 0x0a,
	0x0c, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x63, 0x68, 0x69, 0x70, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0b, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x68, 0x69, 0x70, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70,
	0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x63, 0x68, 0x69, 0x70, 0x5f, 0x70,
	0x65, 0x72, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63,
	0x68, 0x69, 0x70, 0x50, 0x65, 0x72, 0x55, 0x6e, 0x69, 0x74, 0x22, 0x8c, 0x01, 0x0a, 0x0a, 0x44,
	0x65, 0x61, 0x6c, 0x49, 0x6e, 0x53, 0x68, 0x6f, 0x70, 0x12, 0x1d, 0x0a, 0x04, 0x62, 0x65, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65,
	0x61, 0x6c, 0x52, 0x04, 0x62, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x04, 0x69, 0x61, 0x70, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x61,
	0x6c, 0x52, 0x04, 0x69, 0x61, 0x70, 0x73, 0x12, 0x23, 0x0a, 0x07, 0x67, 0x63, 0x61, 0x73, 0x68,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44,
	0x65, 0x61, 0x6c, 0x52, 0x07, 0x67, 0x63, 0x61, 0x73, 0x68, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x03,
	0x73, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x44, 0x65, 0x61, 0x6c, 0x52, 0x03, 0x73, 0x6d, 0x73, 0x22, 0x5f, 0x0a, 0x11, 0x4c, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0xf9, 0x03, 0x0a, 0x0c, 0x45,
	0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x69,
	0x64, 0x5f, 0x64, 0x65, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x64,
	0x44, 0x65, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x69, 0x70, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x68, 0x69, 0x70, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x6c, 0x6f,
	0x63, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x73, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x61, 0x73, 0x68, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x73,
	0x68, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61,
	0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a,
	0x0a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x76, 0x69,
	0x70, 0x5f, 0x6c, 0x76, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x69, 0x70, 0x4c,
	0x76, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x28,
	0x0a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x69,
	0x6e, 0x67, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x2c, 0x0a, 0x12, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x48, 0x61,
	0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x39, 0x0a, 0x12, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x44, 0x65, 0x61, 0x6c, 0x49, 0x6e, 0x53, 0x68, 0x6f, 0x70, 0x12, 0x23, 0x0a, 0x07,
	0x67, 0x63, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x61, 0x6c, 0x52, 0x07, 0x67, 0x63, 0x61, 0x73, 0x68, 0x65,
	0x73, 0x22, 0xf2, 0x01, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x38, 0x0a, 0x0e, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x0d, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x63, 0x75, 0x73, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x43, 0x75, 0x73, 0x6f, 0x72, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x65, 0x76, 0x5f, 0x63, 0x75, 0x73, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x65, 0x76, 0x43, 0x75, 0x73, 0x6f, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x74, 0x6f, 0x22, 0xb6, 0x01, 0x0a, 0x0f, 0x45, 0x78, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x75, 0x73, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x75, 0x73,
	0x6f, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x73, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x22,
	0xd7, 0x02, 0x0a, 0x06, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68,
	0x69, 0x70, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x68, 0x69, 0x70, 0x73,
	0x12, 0x23, 0x0a, 0x0d, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x5f, 0x62, 0x6f, 0x6e, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x42, 0x6f, 0x6e, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x5f, 0x63,
	0x68, 0x69, 0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x62, 0x6f, 0x6e, 0x75,
	0x73, 0x43, 0x68, 0x69, 0x70, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f,
	0x63, 0x68, 0x69, 0x70, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x43, 0x68, 0x69, 0x70, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6b, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x63, 0x73, 0x5f, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x63, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x12, 0x35, 0x0a, 0x17, 0x73, 0x65, 0x63, 0x73, 0x5f, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f,
	0x61, 0x66, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x14, 0x73, 0x65, 0x63, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x41, 0x66, 0x74,
	0x65, 0x72, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x5f, 0x63,
	0x6c, 0x61, 0x69, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x61, 0x6e, 0x43,
	0x6c, 0x61, 0x69, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x75, 0x6d, 0x5f, 0x63, 0x6c, 0x61, 0x69,
	0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x43, 0x6c, 0x61, 0x69,
	0x6d, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x5f,
	0x75, 0x6e, 0x69, 0x78, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74,
	0x43, 0x6c, 0x61, 0x69, 0x6d, 0x55, 0x6e, 0x69, 0x78, 0x22, 0xa1, 0x01, 0x0a, 0x09, 0x44, 0x61,
	0x79, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x2e, 0x0a, 0x0c, 0x69, 0x6e, 0x64, 0x61, 0x79,
	0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x0b, 0x69, 0x6e, 0x64, 0x61,
	0x79, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x30, 0x0a, 0x0d, 0x6f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x0c, 0x6f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x32, 0x0a, 0x0e, 0x6f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x0d,
	0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x22, 0x37, 0x0a,
	0x0b, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x28, 0x0a, 0x07,
	0x64, 0x61, 0x69, 0x6c, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x79, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x07, 0x64,
	0x61, 0x69, 0x6c, 0x69, 0x65, 0x73, 0x2a, 0x68, 0x0a, 0x08, 0x54, 0x79, 0x70, 0x65, 0x43, 0x68,
	0x61, 0x74, 0x12, 0x19, 0x0a, 0x15, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a,
	0x0e, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x10,
	0x01, 0x12, 0x17, 0x0a, 0x13, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x44,
	0x49, 0x52, 0x45, 0x43, 0x54, 0x4d, 0x53, 0x47, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x55, 0x50, 0x10, 0x03,
	0x2a, 0xc5, 0x01, 0x0a, 0x0e, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x1b, 0x45, 0x58, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x45, 0x58, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x57, 0x41, 0x49, 0x54, 0x49, 0x4e, 0x47, 0x10,
	0x01, 0x12, 0x22, 0x0a, 0x1e, 0x45, 0x58, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x5f, 0x42, 0x59, 0x5f, 0x55,
	0x53, 0x45, 0x52, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x45, 0x58, 0x43, 0x48, 0x41, 0x4e, 0x47,
	0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47,
	0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x45, 0x58, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x44, 0x4f, 0x4e, 0x45, 0x10, 0x04, 0x12, 0x1a, 0x0a, 0x16,
	0x45, 0x58, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x10, 0x05, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x69, 0x61, 0x6f, 0x6c, 0x69, 0x6e, 0x6b, 0x2d,
	0x67, 0x61, 0x6d, 0x65, 0x2d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x63, 0x67,
	0x70, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2d, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_common_api_proto_rawDescOnce sync.Once
	file_proto_common_api_proto_rawDescData = file_proto_common_api_proto_rawDesc
)

func file_proto_common_api_proto_rawDescGZIP() []byte {
	file_proto_common_api_proto_rawDescOnce.Do(func() {
		file_proto_common_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_common_api_proto_rawDescData)
	})
	return file_proto_common_api_proto_rawDescData
}

var file_proto_common_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_common_api_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_common_api_proto_goTypes = []interface{}{
	(TypeChat)(0),              // 0: api.TypeChat
	(ExchangeStatus)(0),        // 1: api.ExchangeStatus
	(*Game)(nil),               // 2: api.Game
	(*Layout)(nil),             // 3: api.Layout
	(*GameListResponse)(nil),   // 4: api.GameListResponse
	(*BetListRequest)(nil),     // 5: api.BetListRequest
	(*BetListResponse)(nil),    // 6: api.BetListResponse
	(*Chat)(nil),               // 7: api.Chat
	(*FreeChip)(nil),           // 8: api.FreeChip
	(*FreeChipRequest)(nil),    // 9: api.FreeChipRequest
	(*ListFreeChip)(nil),       // 10: api.ListFreeChip
	(*Deal)(nil),               // 11: api.Deal
	(*DealInShop)(nil),         // 12: api.DealInShop
	(*LeaderBoardRecord)(nil),  // 13: api.LeaderBoardRecord
	(*ExchangeInfo)(nil),       // 14: api.ExchangeInfo
	(*ExchangeDealInShop)(nil), // 15: api.ExchangeDealInShop
	(*ListExchangeInfo)(nil),   // 16: api.ListExchangeInfo
	(*ExchangeRequest)(nil),    // 17: api.ExchangeRequest
	(*Reward)(nil),             // 18: api.Reward
	(*DayReward)(nil),          // 19: api.DayReward
	(*DailyReward)(nil),        // 20: api.DailyReward
}
var file_proto_common_api_proto_depIdxs = []int32{
	3,  // 0: api.Game.layout:type_name -> api.Layout
	2,  // 1: api.GameListResponse.games:type_name -> api.Game
	0,  // 2: api.Chat.type_chat:type_name -> api.TypeChat
	8,  // 3: api.ListFreeChip.freechips:type_name -> api.FreeChip
	11, // 4: api.DealInShop.best:type_name -> api.Deal
	11, // 5: api.DealInShop.iaps:type_name -> api.Deal
	11, // 6: api.DealInShop.gcashes:type_name -> api.Deal
	11, // 7: api.DealInShop.sms:type_name -> api.Deal
	11, // 8: api.ExchangeDealInShop.gcashes:type_name -> api.Deal
	14, // 9: api.ListExchangeInfo.exchange_infos:type_name -> api.ExchangeInfo
	18, // 10: api.DayReward.inday_reward:type_name -> api.Reward
	18, // 11: api.DayReward.online_reward:type_name -> api.Reward
	18, // 12: api.DayReward.online_rewards:type_name -> api.Reward
	19, // 13: api.DailyReward.dailies:type_name -> api.DayReward
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_common_api_proto_init() }
func file_proto_common_api_proto_init() {
	if File_proto_common_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_common_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Game); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Layout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BetListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BetListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FreeChip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FreeChipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFreeChip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DealInShop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderBoardRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeDealInShop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListExchangeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DayReward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DailyReward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_common_api_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_api_proto_goTypes,
		DependencyIndexes: file_proto_common_api_proto_depIdxs,
		EnumInfos:         file_proto_common_api_proto_enumTypes,
		MessageInfos:      file_proto_common_api_proto_msgTypes,
	}.Build()
	File_proto_common_api_proto = out.File
	file_proto_common_api_proto_rawDesc = nil
	file_proto_common_api_proto_goTypes = nil
	file_proto_common_api_proto_depIdxs = nil
}
