// Copyright 2020 The Nakama Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: proto/common_api.proto

// The realtime protocol for the template match engine.

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TypeChat int32

const (
	TypeChat_TYPE_CHAT_UNSPECIFIED TypeChat = 0
	TypeChat_TYPE_CHAT_ROOM        TypeChat = 1
	TypeChat_TYPE_CHAT_DIRECTMSG   TypeChat = 2
	TypeChat_TYPE_CHAT_GROUUP      TypeChat = 3
)

// Enum value maps for TypeChat.
var (
	TypeChat_name = map[int32]string{
		0: "TYPE_CHAT_UNSPECIFIED",
		1: "TYPE_CHAT_ROOM",
		2: "TYPE_CHAT_DIRECTMSG",
		3: "TYPE_CHAT_GROUUP",
	}
	TypeChat_value = map[string]int32{
		"TYPE_CHAT_UNSPECIFIED": 0,
		"TYPE_CHAT_ROOM":        1,
		"TYPE_CHAT_DIRECTMSG":   2,
		"TYPE_CHAT_GROUUP":      3,
	}
)

func (x TypeChat) Enum() *TypeChat {
	p := new(TypeChat)
	*p = x
	return p
}

func (x TypeChat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeChat) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_api_proto_enumTypes[0].Descriptor()
}

func (TypeChat) Type() protoreflect.EnumType {
	return &file_proto_common_api_proto_enumTypes[0]
}

func (x TypeChat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeChat.Descriptor instead.
func (TypeChat) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{0}
}

type Game struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string  `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Active  bool    `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	LobbyId string  `protobuf:"bytes,3,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	Layout  *Layout `protobuf:"bytes,4,opt,name=layout,proto3" json:"layout,omitempty"`
}

func (x *Game) Reset() {
	*x = Game{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{0}
}

func (x *Game) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Game) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Game) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *Game) GetLayout() *Layout {
	if x != nil {
		return x.Layout
	}
	return nil
}

type Layout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Col     int32 `protobuf:"varint,1,opt,name=col,proto3" json:"col,omitempty"`
	Row     int32 `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	ColSpan int32 `protobuf:"varint,3,opt,name=col_span,json=colSpan,proto3" json:"col_span,omitempty"`
	RowSpan int32 `protobuf:"varint,4,opt,name=row_span,json=rowSpan,proto3" json:"row_span,omitempty"`
}

func (x *Layout) Reset() {
	*x = Layout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Layout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layout) ProtoMessage() {}

func (x *Layout) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layout.ProtoReflect.Descriptor instead.
func (*Layout) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{1}
}

func (x *Layout) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *Layout) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *Layout) GetColSpan() int32 {
	if x != nil {
		return x.ColSpan
	}
	return 0
}

func (x *Layout) GetRowSpan() int32 {
	if x != nil {
		return x.RowSpan
	}
	return 0
}

type GameListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameListRequest) Reset() {
	*x = GameListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameListRequest) ProtoMessage() {}

func (x *GameListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameListRequest.ProtoReflect.Descriptor instead.
func (*GameListRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{2}
}

type GameListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Games []*Game `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
}

func (x *GameListResponse) Reset() {
	*x = GameListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameListResponse) ProtoMessage() {}

func (x *GameListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameListResponse.ProtoReflect.Descriptor instead.
func (*GameListResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{3}
}

func (x *GameListResponse) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

type BetListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *BetListRequest) Reset() {
	*x = BetListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetListRequest) ProtoMessage() {}

func (x *BetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetListRequest.ProtoReflect.Descriptor instead.
func (*BetListRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{4}
}

func (x *BetListRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type BetListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bets []int32 `protobuf:"varint,1,rep,packed,name=bets,proto3" json:"bets,omitempty"`
}

func (x *BetListResponse) Reset() {
	*x = BetListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetListResponse) ProtoMessage() {}

func (x *BetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetListResponse.ProtoReflect.Descriptor instead.
func (*BetListResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{5}
}

func (x *BetListResponse) GetBets() []int32 {
	if x != nil {
		return x.Bets
	}
	return nil
}

type Chat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeChat TypeChat `protobuf:"varint,1,opt,name=type_chat,json=typeChat,proto3,enum=api.TypeChat" json:"type_chat,omitempty"`
	Id       string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Content  string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Chat) Reset() {
	*x = Chat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{6}
}

func (x *Chat) GetTypeChat() TypeChat {
	if x != nil {
		return x.TypeChat
	}
	return TypeChat_TYPE_CHAT_UNSPECIFIED
}

func (x *Chat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chat) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Profile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	AvatarUrl     string `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	AccountChip   int64  `protobuf:"varint,5,opt,name=account_chip,json=accountChip,proto3" json:"account_chip,omitempty"`
	BankChip      int64  `protobuf:"varint,6,opt,name=bank_chip,json=bankChip,proto3" json:"bank_chip,omitempty"`
	RefCode       string `protobuf:"bytes,7,opt,name=ref_code,json=refCode,proto3" json:"ref_code,omitempty"`
	LangTag       string `protobuf:"bytes,8,opt,name=lang_tag,json=langTag,proto3" json:"lang_tag,omitempty"`
	LinkGroup     string `protobuf:"bytes,9,opt,name=link_group,json=linkGroup,proto3" json:"link_group,omitempty"`
	LinkFanpageFb string `protobuf:"bytes,10,opt,name=link_fanpage_fb,json=linkFanpageFb,proto3" json:"link_fanpage_fb,omitempty"`
	AppConfig     string `protobuf:"bytes,11,opt,name=app_config,json=appConfig,proto3" json:"app_config,omitempty"`
}

func (x *Profile) Reset() {
	*x = Profile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_proto_common_api_proto_rawDescGZIP(), []int{7}
}

func (x *Profile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Profile) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Profile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Profile) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Profile) GetAccountChip() int64 {
	if x != nil {
		return x.AccountChip
	}
	return 0
}

func (x *Profile) GetBankChip() int64 {
	if x != nil {
		return x.BankChip
	}
	return 0
}

func (x *Profile) GetRefCode() string {
	if x != nil {
		return x.RefCode
	}
	return ""
}

func (x *Profile) GetLangTag() string {
	if x != nil {
		return x.LangTag
	}
	return ""
}

func (x *Profile) GetLinkGroup() string {
	if x != nil {
		return x.LinkGroup
	}
	return ""
}

func (x *Profile) GetLinkFanpageFb() string {
	if x != nil {
		return x.LinkFanpageFb
	}
	return ""
}

func (x *Profile) GetAppConfig() string {
	if x != nil {
		return x.AppConfig
	}
	return ""
}

var File_proto_common_api_proto protoreflect.FileDescriptor

var file_proto_common_api_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x72, 0x0a,
	0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x06,
	0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75,
	0x74, 0x22, 0x62, 0x0a, 0x06, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63,
	0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x6f, 0x6c, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x12,
	0x19, 0x0a, 0x08, 0x63, 0x6f, 0x6c, 0x5f, 0x73, 0x70, 0x61, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x63, 0x6f, 0x6c, 0x53, 0x70, 0x61, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f,
	0x77, 0x5f, 0x73, 0x70, 0x61, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x6f,
	0x77, 0x53, 0x70, 0x61, 0x6e, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x33, 0x0a, 0x10, 0x47, 0x61, 0x6d, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05,
	0x67, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x05, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x24, 0x0a,
	0x0e, 0x42, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x22, 0x25, 0x0a, 0x0f, 0x42, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x65, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x62, 0x65, 0x74, 0x73, 0x22, 0x5c, 0x0a, 0x04, 0x43, 0x68,
	0x61, 0x74, 0x12, 0x2a, 0x0a, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x43, 0x68, 0x61, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xd2, 0x02, 0x0a, 0x07, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x63, 0x68, 0x69,
	0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x43, 0x68, 0x69, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x63, 0x68, 0x69,
	0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6b, 0x43, 0x68, 0x69,
	0x70, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x66, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x66, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6c, 0x61, 0x6e, 0x67, 0x54, 0x61, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x6b, 0x5f,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x69, 0x6e,
	0x6b, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x66,
	0x61, 0x6e, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x62, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x6c, 0x69, 0x6e, 0x6b, 0x46, 0x61, 0x6e, 0x70, 0x61, 0x67, 0x65, 0x46, 0x62, 0x12, 0x1d,
	0x0a, 0x0a, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2a, 0x68, 0x0a,
	0x08, 0x54, 0x79, 0x70, 0x65, 0x43, 0x68, 0x61, 0x74, 0x12, 0x19, 0x0a, 0x15, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x48, 0x41,
	0x54, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x4d, 0x53, 0x47, 0x10,
	0x02, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x47,
	0x52, 0x4f, 0x55, 0x55, 0x50, 0x10, 0x03, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x69, 0x61, 0x6f, 0x6c, 0x69, 0x6e, 0x6b, 0x2d, 0x67,
	0x61, 0x6d, 0x65, 0x2d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x63, 0x67, 0x70,
	0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2d, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_common_api_proto_rawDescOnce sync.Once
	file_proto_common_api_proto_rawDescData = file_proto_common_api_proto_rawDesc
)

func file_proto_common_api_proto_rawDescGZIP() []byte {
	file_proto_common_api_proto_rawDescOnce.Do(func() {
		file_proto_common_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_common_api_proto_rawDescData)
	})
	return file_proto_common_api_proto_rawDescData
}

var file_proto_common_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_common_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_common_api_proto_goTypes = []interface{}{
	(TypeChat)(0),            // 0: api.TypeChat
	(*Game)(nil),             // 1: api.Game
	(*Layout)(nil),           // 2: api.Layout
	(*GameListRequest)(nil),  // 3: api.GameListRequest
	(*GameListResponse)(nil), // 4: api.GameListResponse
	(*BetListRequest)(nil),   // 5: api.BetListRequest
	(*BetListResponse)(nil),  // 6: api.BetListResponse
	(*Chat)(nil),             // 7: api.Chat
	(*Profile)(nil),          // 8: api.Profile
}
var file_proto_common_api_proto_depIdxs = []int32{
	2, // 0: api.Game.layout:type_name -> api.Layout
	1, // 1: api.GameListResponse.games:type_name -> api.Game
	0, // 2: api.Chat.type_chat:type_name -> api.TypeChat
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_common_api_proto_init() }
func file_proto_common_api_proto_init() {
	if File_proto_common_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_common_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Game); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Layout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BetListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BetListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Profile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_common_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_api_proto_goTypes,
		DependencyIndexes: file_proto_common_api_proto_depIdxs,
		EnumInfos:         file_proto_common_api_proto_enumTypes,
		MessageInfos:      file_proto_common_api_proto_msgTypes,
	}.Build()
	File_proto_common_api_proto = out.File
	file_proto_common_api_proto_rawDesc = nil
	file_proto_common_api_proto_goTypes = nil
	file_proto_common_api_proto_depIdxs = nil
}
