// Copyright 2020 The Nakama Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: proto/match_api.proto

// The realtime protocol for the template match engine.

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The complete set of rpc used for communication between clients and server.
type RPCCode int32

const (
	// No opcode specified. Unused.
	RPCCode_RPC_FIND_MATCH   RPCCode = 0
	RPCCode_RPC_CREATE_MATCH RPCCode = 1
)

// Enum value maps for RPCCode.
var (
	RPCCode_name = map[int32]string{
		0: "RPC_FIND_MATCH",
		1: "RPC_CREATE_MATCH",
	}
	RPCCode_value = map[string]int32{
		"RPC_FIND_MATCH":   0,
		"RPC_CREATE_MATCH": 1,
	}
)

func (x RPCCode) Enum() *RPCCode {
	p := new(RPCCode)
	*p = x
	return p
}

func (x RPCCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RPCCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_match_api_proto_enumTypes[0].Descriptor()
}

func (RPCCode) Type() protoreflect.EnumType {
	return &file_proto_match_api_proto_enumTypes[0]
}

func (x RPCCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RPCCode.Descriptor instead.
func (RPCCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_match_api_proto_rawDescGZIP(), []int{0}
}

// Payload for an RPC request to find a match.
type RpcFindMatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// User can choose a fast or normal speed match.
	MarkUnit     int32  `protobuf:"varint,1,opt,name=mark_unit,json=markUnit,proto3" json:"mark_unit,omitempty"`
	GameCode     string `protobuf:"bytes,2,opt,name=game_code,json=gameCode,proto3" json:"game_code,omitempty"`
	WithNonOpen  bool   `protobuf:"varint,3,opt,name=with_non_open,json=withNonOpen,proto3" json:"with_non_open,omitempty"`
	Create       bool   `protobuf:"varint,4,opt,name=create,proto3" json:"create,omitempty"`
	MockCodeCard int32  `protobuf:"varint,5,opt,name=mock_code_card,json=mockCodeCard,proto3" json:"mock_code_card,omitempty"`
}

func (x *RpcFindMatchRequest) Reset() {
	*x = RpcFindMatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_match_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcFindMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcFindMatchRequest) ProtoMessage() {}

func (x *RpcFindMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcFindMatchRequest.ProtoReflect.Descriptor instead.
func (*RpcFindMatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_match_api_proto_rawDescGZIP(), []int{0}
}

func (x *RpcFindMatchRequest) GetMarkUnit() int32 {
	if x != nil {
		return x.MarkUnit
	}
	return 0
}

func (x *RpcFindMatchRequest) GetGameCode() string {
	if x != nil {
		return x.GameCode
	}
	return ""
}

func (x *RpcFindMatchRequest) GetWithNonOpen() bool {
	if x != nil {
		return x.WithNonOpen
	}
	return false
}

func (x *RpcFindMatchRequest) GetCreate() bool {
	if x != nil {
		return x.Create
	}
	return false
}

func (x *RpcFindMatchRequest) GetMockCodeCard() int32 {
	if x != nil {
		return x.MockCodeCard
	}
	return 0
}

type Match struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId      string `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Size         int32  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	MaxSize      int32  `protobuf:"varint,3,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	Name         string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	MarkUnit     int32  `protobuf:"varint,5,opt,name=mark_unit,json=markUnit,proto3" json:"mark_unit,omitempty"`
	Open         bool   `protobuf:"varint,6,opt,name=open,proto3" json:"open,omitempty"`
	MockCodeCard int32  `protobuf:"varint,7,opt,name=mock_code_card,json=mockCodeCard,proto3" json:"mock_code_card,omitempty"`
}

func (x *Match) Reset() {
	*x = Match{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_match_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_proto_match_api_proto_rawDescGZIP(), []int{1}
}

func (x *Match) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *Match) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Match) GetMaxSize() int32 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *Match) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Match) GetMarkUnit() int32 {
	if x != nil {
		return x.MarkUnit
	}
	return 0
}

func (x *Match) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

func (x *Match) GetMockCodeCard() int32 {
	if x != nil {
		return x.MockCodeCard
	}
	return 0
}

// Payload for an RPC response containing match IDs the user can join.
type RpcFindMatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// One or more matches that fit the user's request.
	Matches []*Match `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
}

func (x *RpcFindMatchResponse) Reset() {
	*x = RpcFindMatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_match_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcFindMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcFindMatchResponse) ProtoMessage() {}

func (x *RpcFindMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcFindMatchResponse.ProtoReflect.Descriptor instead.
func (*RpcFindMatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_match_api_proto_rawDescGZIP(), []int{2}
}

func (x *RpcFindMatchResponse) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

// Payload for an RPC request to find a match.
type RpcCreateMatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MarkUnit int32  `protobuf:"varint,1,opt,name=mark_unit,json=markUnit,proto3" json:"mark_unit,omitempty"`
	GameCode string `protobuf:"bytes,2,opt,name=game_code,json=gameCode,proto3" json:"game_code,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *RpcCreateMatchRequest) Reset() {
	*x = RpcCreateMatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_match_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcCreateMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcCreateMatchRequest) ProtoMessage() {}

func (x *RpcCreateMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcCreateMatchRequest.ProtoReflect.Descriptor instead.
func (*RpcCreateMatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_match_api_proto_rawDescGZIP(), []int{3}
}

func (x *RpcCreateMatchRequest) GetMarkUnit() int32 {
	if x != nil {
		return x.MarkUnit
	}
	return 0
}

func (x *RpcCreateMatchRequest) GetGameCode() string {
	if x != nil {
		return x.GameCode
	}
	return ""
}

func (x *RpcCreateMatchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RpcCreateMatchRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Payload for an RPC response containing match IDs the user can join.
type RpcCreateMatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// One or more matches that fit the user's request.
	MatchId string `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
}

func (x *RpcCreateMatchResponse) Reset() {
	*x = RpcCreateMatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_match_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcCreateMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcCreateMatchResponse) ProtoMessage() {}

func (x *RpcCreateMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcCreateMatchResponse.ProtoReflect.Descriptor instead.
func (*RpcCreateMatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_match_api_proto_rawDescGZIP(), []int{4}
}

func (x *RpcCreateMatchResponse) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type Bet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enable   bool  `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	MarkUnit int32 `protobuf:"varint,2,opt,name=mark_unit,json=markUnit,proto3" json:"mark_unit,omitempty"` // mức cược (chip)
}

func (x *Bet) Reset() {
	*x = Bet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_match_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bet) ProtoMessage() {}

func (x *Bet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bet.ProtoReflect.Descriptor instead.
func (*Bet) Descriptor() ([]byte, []int) {
	return file_proto_match_api_proto_rawDescGZIP(), []int{5}
}

func (x *Bet) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Bet) GetMarkUnit() int32 {
	if x != nil {
		return x.MarkUnit
	}
	return 0
}

type Bets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bets []*Bet `protobuf:"bytes,1,rep,name=bets,proto3" json:"bets,omitempty"`
}

func (x *Bets) Reset() {
	*x = Bets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_match_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bets) ProtoMessage() {}

func (x *Bets) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bets.ProtoReflect.Descriptor instead.
func (*Bets) Descriptor() ([]byte, []int) {
	return file_proto_match_api_proto_rawDescGZIP(), []int{6}
}

func (x *Bets) GetBets() []*Bet {
	if x != nil {
		return x.Bets
	}
	return nil
}

var File_proto_match_api_proto protoreflect.FileDescriptor

var file_proto_match_api_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0xb1, 0x01, 0x0a,
	0x13, 0x52, 0x70, 0x63, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x5f, 0x75, 0x6e, 0x69,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x61, 0x72, 0x6b, 0x55, 0x6e, 0x69,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x22,
	0x0a, 0x0d, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x6e, 0x6f, 0x6e, 0x5f, 0x6f, 0x70, 0x65, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x77, 0x69, 0x74, 0x68, 0x4e, 0x6f, 0x6e, 0x4f, 0x70,
	0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x6f,
	0x63, 0x6b, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x6d, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x43, 0x61, 0x72, 0x64,
	0x22, 0xbc, 0x01, 0x0a, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x78,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x61, 0x78,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x72, 0x6b,
	0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x61, 0x72,
	0x6b, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x6f, 0x63,
	0x6b, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x6d, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x43, 0x61, 0x72, 0x64, 0x22,
	0x3c, 0x0a, 0x14, 0x52, 0x70, 0x63, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x22, 0x81, 0x01,
	0x0a, 0x15, 0x52, 0x70, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x5f,
	0x75, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x61, 0x72, 0x6b,
	0x55, 0x6e, 0x69, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x22, 0x33, 0x0a, 0x16, 0x52, 0x70, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x03, 0x42, 0x65, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x5f, 0x75, 0x6e,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x61, 0x72, 0x6b, 0x55, 0x6e,
	0x69, 0x74, 0x22, 0x24, 0x0a, 0x04, 0x42, 0x65, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x04, 0x62, 0x65,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42,
	0x65, 0x74, 0x52, 0x04, 0x62, 0x65, 0x74, 0x73, 0x2a, 0x33, 0x0a, 0x07, 0x52, 0x50, 0x43, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x50, 0x43, 0x5f, 0x46, 0x49, 0x4e, 0x44, 0x5f,
	0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x50, 0x43, 0x5f, 0x43,
	0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x01, 0x42, 0x38, 0x5a,
	0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x69, 0x61, 0x6f,
	0x6c, 0x69, 0x6e, 0x6b, 0x2d, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x2f, 0x63, 0x67, 0x70, 0x2d, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2d, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_match_api_proto_rawDescOnce sync.Once
	file_proto_match_api_proto_rawDescData = file_proto_match_api_proto_rawDesc
)

func file_proto_match_api_proto_rawDescGZIP() []byte {
	file_proto_match_api_proto_rawDescOnce.Do(func() {
		file_proto_match_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_match_api_proto_rawDescData)
	})
	return file_proto_match_api_proto_rawDescData
}

var file_proto_match_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_match_api_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_match_api_proto_goTypes = []interface{}{
	(RPCCode)(0),                   // 0: api.RPCCode
	(*RpcFindMatchRequest)(nil),    // 1: api.RpcFindMatchRequest
	(*Match)(nil),                  // 2: api.Match
	(*RpcFindMatchResponse)(nil),   // 3: api.RpcFindMatchResponse
	(*RpcCreateMatchRequest)(nil),  // 4: api.RpcCreateMatchRequest
	(*RpcCreateMatchResponse)(nil), // 5: api.RpcCreateMatchResponse
	(*Bet)(nil),                    // 6: api.Bet
	(*Bets)(nil),                   // 7: api.Bets
}
var file_proto_match_api_proto_depIdxs = []int32{
	2, // 0: api.RpcFindMatchResponse.matches:type_name -> api.Match
	6, // 1: api.Bets.bets:type_name -> api.Bet
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_match_api_proto_init() }
func file_proto_match_api_proto_init() {
	if File_proto_match_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_match_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcFindMatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_match_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Match); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_match_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcFindMatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_match_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcCreateMatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_match_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcCreateMatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_match_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_match_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_match_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_match_api_proto_goTypes,
		DependencyIndexes: file_proto_match_api_proto_depIdxs,
		EnumInfos:         file_proto_match_api_proto_enumTypes,
		MessageInfos:      file_proto_match_api_proto_msgTypes,
	}.Build()
	File_proto_match_api_proto = out.File
	file_proto_match_api_proto_rawDesc = nil
	file_proto_match_api_proto_goTypes = nil
	file_proto_match_api_proto_depIdxs = nil
}
